project_id = "qrxvkbcuggeitgxbbgrd"

[functions.seed-data]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.delete-users]
verify_jwt = false
