// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-schools.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [
      { type: "text", text: "Ch\u01B0a \u0111\u0103ng nh\u1EADp / Not authenticated." }
    ],
    isError: true
  };
}
function textResult(value) {
  return { content: [{ type: "text", text: JSON.stringify(value) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-schools.ts
var list_schools_default = defineTool({
  name: "list_schools",
  title: "List my schools",
  description: "List the schools (\u0111\u01A1n v\u1ECB/tr\u01B0\u1EDDng) the signed-in user belongs to, with the school id needed by other tools.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("school_memberships").select("school_id, role, status, schools(id, name)").eq("user_id", ctx.getUserId()).eq("status", "active");
    if (error) return errorResult(error.message);
    const schools = (data ?? []).map((m) => ({
      school_id: m.school_id,
      name: m.schools?.name ?? null,
      role: m.role
    }));
    return { ...textResult(schools), structuredContent: { schools } };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool2({
  name: "list_tasks",
  title: "List tasks",
  description: "List assigned work items (c\xF4ng vi\u1EC7c & ti\u1EBFn \u0111\u1ED9) for a school, optionally filtered by status or category, ordered by deadline.",
  inputSchema: {
    school_id: z.string().describe("School id from list_schools."),
    status: z.string().optional().describe("Filter by task status, e.g. pending or completed."),
    category: z.string().optional().describe("Filter by task category."),
    limit: z.number().optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ school_id, status, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tasks").select("id, title, description, category, status, deadline, completed_at, assignee_id, created_at").eq("school_id", school_id).order("deadline", { ascending: true, nullsFirst: false }).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (status) query = query.eq("status", status);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return { ...textResult(data ?? []), structuredContent: { tasks: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_task_default = defineTool3({
  name: "create_task",
  title: "Create task",
  description: "Create a new work item (c\xF4ng vi\u1EC7c) for a school. The task is created as the signed-in user.",
  inputSchema: {
    school_id: z2.string().describe("School id from list_schools."),
    title: z2.string().describe("Task title."),
    category: z2.string().describe("Task category, e.g. party, professional, boarding, youth_union."),
    description: z2.string().optional().describe("Task details."),
    deadline: z2.string().optional().describe("Deadline as an ISO date, e.g. 2026-08-01.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ school_id, title, category, description, deadline }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const trimmed = title.trim();
    if (!trimmed) return errorResult("Title is required.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({
      school_id,
      title: trimmed,
      category,
      description: description?.trim() || null,
      deadline: deadline || null,
      created_by: ctx.getUserId()
    }).select("id, title, category, status, deadline").single();
    if (error) return errorResult(error.message);
    return { ...textResult(data), structuredContent: { task: data } };
  }
});

// src/lib/mcp/tools/list-students.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_students_default = defineTool4({
  name: "list_students",
  title: "List students",
  description: "List students (h\u1ECDc sinh) of a school, optionally searching by name or student code and filtering boarding students.",
  inputSchema: {
    school_id: z3.string().describe("School id from list_schools."),
    search: z3.string().optional().describe("Search text matched against full name or student code."),
    boarding_only: z3.boolean().optional().describe("Only return boarding (n\u1ED9i tr\xFA) students."),
    limit: z3.number().optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ school_id, search, boarding_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("students").select("id, student_code, full_name, gender, date_of_birth, is_boarding, room_number, class_id, classes(name)").eq("school_id", school_id).eq("is_active", true).limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (boarding_only) query = query.eq("is_boarding", true);
    if (search?.trim()) {
      const s = search.trim();
      query = query.or(`full_name.ilike.%${s}%,student_code.ilike.%${s}%`);
    }
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return { ...textResult(data ?? []), structuredContent: { students: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qrxvkbcuggeitgxbbgrd";
var mcp_default = defineMcp({
  name: "noitrubantru-mcp",
  title: "Qu\u1EA3n l\xFD n\u1ED9i tr\xFA/b\xE1n tr\xFA",
  version: "0.1.0",
  instructions: "Tools for the boarding/semi-boarding school management app. Call `list_schools` first to get a school_id, then use `list_tasks`, `create_task`, or `list_students` with that id. All data is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_schools_default, list_tasks_default, create_task_default, list_students_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
